### ISSUE TITLE
Did not recompile .coffee before publish

### ISSUE THREAD

**Issue by zkochan** [Kikobeats/cb2promise#8]
I see you removed `pinkie-promise` from .coffee and package.json. But `pinkie-promise` is still used in `index.js`.

cb2promise fails because of this

```
Error: Cannot find module 'pinkie-promise'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/pnpm/pnpm-file-reporter/node_modules/.registry.npmjs.org/cb2promise/1.0.6/node_modules/cb2promise/index.js:3:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by Kikobeats** [comment]
ops, that's true, I'm going to fix now

**Comment by Kikobeats** [comment]
is it fixed?

**Comment by zkochan** [comment]
yes, thanks!

**Comment by Kikobeats** [comment]
nice!

I'm thinking in a better implementation, I ping you in the PR
